name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: Tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 'latest'
      - run: pwd && perl -V
      - run: cpanm --installdeps --notest .
      - run: prove -lv t
      - name: Archive CPAN logs on Unix
        if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: cpan_log
          path: /home/runner/.cpanm/work/*/build.log
          retention-days: 5

  coverage:
    runs-on: ubuntu-latest
    container: davorg/perl-coveralls:latest
    name: Test coverage
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: cpanm -n --installdeps .
      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HARNESS_PERL_SWITCHES: -MDevel::Cover
        run: prove -lv t && cover -report Coveralls -ignore_re t/

